# Generated by Django 6.0.5 on 2026-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='docker_command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='docker_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='docker_ports',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='dockerfile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reto',
            name='tiene_docker',
            field=models.BooleanField(default=False),
        ),
    ]
