# Generated by Django 6.0.5 on 2026-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reto_docker_command_reto_docker_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='docker_image_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
